Repository ITurres/spacex-travelers-hub, pull requests merged in 2023-07, with the labels that each got.

#26 Install basic dependencies - Setup ⚛️ :checkered_flag:
  .babelrc
  .eslintrc.json
  .github/workflows/linters.yml
  .gitignore
  .stylelintrc.json
  README.md
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.jsx
  src/index.jsx
  src/pages/missions.jsx
  src/pages/rockets.jsx
  src/redux/config-store.js
  src/redux/missions/missions-slice.js
  src/redux/rockets/rockets-slice.js
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/base/normalize.css
  src/styles/index.css
Labels: enhancement

#27 Create website header with empty nav - Setup (group task) :eyes:
  .babelrc
  .eslintrc.json
  package-lock.json
  package.json
  src/App.jsx
  src/components/header.jsx
  src/images/planet.png
  src/index.jsx
  src/styles/header.css
Labels: enhancement

#28 Create empty My profile - Setup
  package-lock.json
  package.json
  public/manifest.json
  src/components/header.jsx
  src/styles/header.css
Labels: enhancement

#30 Fetch and Store Rockets Data :100:
  package-lock.json
  package.json
  src/App.jsx
  src/index.jsx
  src/redux/config-store.js
  src/redux/rockets/rockets-slice.js
Labels: enhancement

#31 Display rockets - Lists render :ok_hand:
  package-lock.json
  package.json
  src/App.jsx
  src/components/rockets/RocketCard.jsx
  src/components/rockets/RocketList.jsx
  src/pages/rockets.jsx
Labels: enhancement

#32 Issue #20 | Feature/missions basic structure
  src/App.jsx
  src/pages/MissionsPage.jsx
  src/pages/missions.jsx
Labels: enhancement

#33 Implement rocket booking redux action 🛰️📝
  src/components/rockets/RocketCard.jsx
  src/redux/rockets/rockets-slice.js
Labels: enhancement

#34 Implement rocket booking cancellation Redux action :runner:
  src/components/rockets/RocketCard.jsx
  src/redux/rockets/rockets-slice.js
Labels: enhancement

#36 Issue #18 | Feature/fetch-missions
  src/pages/MissionsPage.jsx
  src/redux/config-store.js
  src/redux/missions/missions-slice.js
Labels: enhancement

#35 Added switch badges for Rockets - Conditional components 🏷️
  src/components/rockets/RocketCard.jsx
Labels: enhancement

#37 Display filtered reserved rockets in My profile :mag_right: :bust_in_silhouette:
  src/App.jsx
  src/pages/ProfilePage.jsx
  src/redux/rockets/rockets-slice.js
Labels: enhancement

#38 Issue #15🎫 - Added Feature: display missions / list render
  src/components/missions/MissionsList.jsx
  src/pages/MissionsPage.jsx
  src/styles/index.css
Labels: enhancement

#39 Issue #10🎫 - Feature: actions mission joining
  src/components/missions/MissionRow.jsx
  src/components/missions/MissionsList.jsx
  src/redux/missions/missions-slice.js
Labels: enhancement

#44 Issue #40🎫 - Feature: Feature/final touches
  LICENSE
  README.md
  package-lock.json
  package.json
  public/index.html
  public/planet.png
  src/App.jsx
  src/components/__tests__/Header.test.js
  src/components/__tests__/MissionRow.test.js
  src/components/__tests__/MissionsList.test.js
  src/components/__tests__/RocketList.test.js
  src/components/__tests__/RocketsCard.test.js
  src/components/missions/MissionRow.jsx
  src/pages/RocketPage.jsx
  src/pages/__tests__/MissionsPage.test.js
  src/pages/__tests__/RocketPage.test.js
  src/redux/__tests__/missions-slice.test.js
  src/redux/__tests__/rocket-silce.test.js
Labels: documentation, enhancement, tests

#45 Space Travelers' Hub App Milestone Reached - Completed :100:
  .babelrc
  .eslintrc.json
  .github/workflows/linters.yml
  .gitignore
  .stylelintrc.json
  LICENSE
  README.md
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  public/planet.png
  public/robots.txt
  src/App.jsx
  src/components/__tests__/Header.test.js
  src/components/__tests__/MissionRow.test.js
  src/components/__tests__/MissionsList.test.js
  src/components/__tests__/RocketList.test.js
  src/components/__tests__/RocketsCard.test.js
  src/components/header.jsx
  src/components/missions/MissionRow.jsx
  src/components/missions/MissionsList.jsx
  src/components/rockets/RocketCard.jsx
  src/components/rockets/RocketList.jsx
  src/images/planet.png
  src/index.jsx
  src/pages/MissionsPage.jsx
  src/pages/ProfilePage.jsx
  src/pages/RocketPage.jsx
  src/pages/__tests__/MissionsPage.test.js
  src/pages/__tests__/RocketPage.test.js
  src/redux/__tests__/missions-slice.test.js
  src/redux/__tests__/rocket-silce.test.js
  src/redux/config-store.js
  src/redux/missions/missions-slice.js
  src/redux/rockets/rockets-slice.js
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/base/normalize.css
  src/styles/header.css
  src/styles/index.css
Labels: documentation, enhancement, setup, tests
